#ifndef TKTEMOTEJOY_HANDLER_COMMON_CALCRANGEDIRECTION_H
#define TKTEMOTEJOY_HANDLER_COMMON_CALCRANGEDIRECTION_H

#include <linux/input.h>

int calcRangeDirection(
    const __s32
    , const __s32
);

#endif  // TKTEMOTEJOY_HANDLER_COMMON_CALCRANGEDIRECTION_H
