#ifndef TKTEMOTEJOY_HANDLER_COMMON_CALCMINTOCENTER_H
#define TKTEMOTEJOY_HANDLER_COMMON_CALCMINTOCENTER_H

#include <linux/input.h>

__s32 calcMinToCenter(
    const __s32
    , const __s32
);

#endif  // TKTEMOTEJOY_HANDLER_COMMON_CALCMINTOCENTER_H
